# Generated by Django 3.1.2 on 2020-11-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0003_userprofile_bio'),
        ('boards', '0026_auto_20201123_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('archived', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='boards.board')),
                ('watched_by', models.ManyToManyField(related_name='watching_lists', to='userauth.UserProfile')),
            ],
        ),
    ]
