# Generated by Django 3.1.2 on 2020-10-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_team', models.CharField(choices=[('HR', 'Human Resorce'), ('MT', 'Marketing'), ('OP', 'Operations'), ('SR', 'Sales CRM'), ('ED', 'Education'), ('SB', 'Small Business'), ('EI', 'Engineering-IT'), ('OT', 'Other')], default='OT', max_length=2)),
                ('desc', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('website', models.URLField(null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(related_name='teams', to='userauth.UserProfile')),
            ],
        ),
    ]
