# Generated by Django 3.1.2 on 2020-10-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('boards', '0002_auto_20201026_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('permission_level', models.IntegerField(choices=[(1, 'organization'), (2, 'private'), (3, 'team')], default=2)),
                ('isclosed', models.BooleanField(default=False)),
                ('guests', models.ManyToManyField(related_name='boards', to='userauth.UserProfile')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='boards.team')),
            ],
        ),
    ]
