# Generated by Django 3.1.2 on 2020-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('boards', '0003_auto_20201026_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='admins',
            field=models.ManyToManyField(related_name='admin_in_boards', to='userauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='board',
            name='starred_by',
            field=models.ManyToManyField(related_name='starred_boards', to='userauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='board',
            name='watched_by',
            field=models.ManyToManyField(related_name='watching_boards', to='userauth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='board',
            name='guests',
            field=models.ManyToManyField(related_name='guest_in_boards', to='userauth.UserProfile'),
        ),
    ]
