# Generated by Django 3.1.2 on 2020-10-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('boards', '0004_auto_20201026_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='boards', to='userauth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='board',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
