# Generated by Django 3.1.2 on 2020-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20201026_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='personal',
            field=models.BooleanField(default=False),
        ),
    ]
