# Generated by Django 3.1.2 on 2020-10-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_board_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.AlterField(
            model_name='board',
            name='permission_level',
            field=models.CharField(choices=[('or', 'Organization'), ('pr', 'Private'), ('tm', 'team')], default='tm', max_length=2),
        ),
    ]
