# Generated by Django 3.1.2 on 2020-10-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20201026_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_join', models.BooleanField(default=True)),
                ('card_cover', models.BooleanField(default=True)),
                ('pref_comment', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Team Members and Guest Members'), (2, 'Only team or members associated with object(card/list/board)'), (3, 'Only observers'), (4, 'Public')], default=0)),
                ('pref_invitation', models.IntegerField(choices=[(0, 'Only admins can send invitation'), (1, 'Only Members can send invitation')], default=1)),
                ('permission_level', models.IntegerField(choices=[(0, 'Team Members and Guest Members'), (1, 'Only admins and members'), (2, 'Public')], default=0)),
                ('pref_voting', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Team Members and Guest Members'), (2, 'Only team or members associated with object(card/list/board)'), (3, 'Only observers'), (4, 'Public')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='permission_level',
        ),
        migrations.AddField(
            model_name='board',
            name='preference',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board', to='boards.preference'),
        ),
    ]
