# Generated by Django 3.1.2 on 2020-10-28 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20201028_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='isclosed',
            new_name='is_closed',
        ),
        migrations.AlterField(
            model_name='preference',
            name='board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='boards.board'),
        ),
    ]
