# Generated by Django 3.1.2 on 2020-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('boards', '0010_auto_20201028_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='board',
            name='personal',
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='member_in_boards', to='userauth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='card_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='permission_level',
            field=models.IntegerField(choices=[(1, 'Admin,Board members'), (2, 'Admin, Board Members'), (3, 'Admin, Board Members, and team members'), (4, 'anyone')], default=3),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref_comment',
            field=models.IntegerField(choices=[(1, 'Disabled'), (2, 'Admin,Board members'), (3, 'Admin, Board Members and Guests'), (4, 'Admin, Board Members, Guests and team members'), (5, 'anyone')], default=1),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref_invitation',
            field=models.IntegerField(choices=[(0, 'Only admins can add and remove members from this board'), (1, 'Only Members can add and remove members from this board')], default=1),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref_voting',
            field=models.IntegerField(choices=[(1, 'Disabled'), (2, 'Admin,Board members'), (3, 'Admin, Board Members and Guests'), (4, 'Admin, Board Members, Guests and team members'), (5, 'anyone')], default=1),
        ),
    ]
