# Generated by Django 3.1.2 on 2020-10-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('boards', '0011_auto_20201028_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='permission_level',
            field=models.IntegerField(choices=[(1, 'Admins'), (2, 'Admin and Board Members'), (3, 'Admin, Board Members, and team members'), (4, 'anyone')], default=3),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref_comment',
            field=models.IntegerField(choices=[(1, 'Disabled'), (2, 'Admins'), (3, 'Admin and Board Members'), (4, 'Admin, Board Members, Guests and team members'), (5, 'anyone')], default=1),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref_voting',
            field=models.IntegerField(choices=[(1, 'Disabled'), (2, 'Admins'), (3, 'Admin and Board Members'), (4, 'Admin, Board Members, Guests and team members'), (5, 'anyone')], default=1),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('archived', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='boards.board')),
                ('wathched_by', models.ManyToManyField(related_name='lists_watching', to='userauth.UserProfile')),
            ],
        ),
    ]
