# Generated by Django 3.1.2 on 2020-10-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('boards', '0012_auto_20201029_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('archived', models.BooleanField(default=False)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.list')),
                ('members', models.ManyToManyField(related_name='member_in_card', to='userauth.UserProfile')),
                ('watched_by', models.ManyToManyField(related_name='watching_cards', to='userauth.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Checklist', max_length=50)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='boards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Attached_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_link', to='boards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Attached_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_file', to='boards.card')),
            ],
        ),
    ]
