# Generated by Django 3.1.2 on 2020-11-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_attached_file_attached_link_card_checklist_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='wathched_by',
            new_name='watched_by',
        ),
    ]
