# Generated by Django 3.1.2 on 2020-11-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20201101_1539'),
        ('boards', '0014_auto_20201102_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attached_file',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_files', to='boards.card'),
        ),
        migrations.AlterField(
            model_name='attached_link',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_links', to='boards.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='members',
            field=models.ManyToManyField(null=True, related_name='member_in_card', to='userauth.UserProfile'),
        ),
    ]
