# Generated by Django 3.1.2 on 2020-11-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20201101_1539'),
        ('boards', '0016_auto_20201106_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=30)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='boards.board')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='voted_by',
            field=models.ManyToManyField(related_name='voted_cards', to='userauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='preference',
            name='voting_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
