# Generated by Django 3.1.2 on 2020-11-07 11:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_userprofile_bio'),
        ('boards', '0017_auto_20201107_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity', to='userauth.userprofile')),
            ],
        ),
    ]
