# Generated by Django 3.1.2 on 2020-11-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_auto_20201107_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='boards.card'),
        ),
    ]
