# Generated by Django 3.1.2 on 2020-11-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_userprofile_bio'),
        ('boards', '0020_auto_20201107_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['index', 'id']},
        ),
        migrations.RemoveField(
            model_name='card',
            name='priority',
        ),
        migrations.AddField(
            model_name='card',
            name='index',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='watched_by',
            field=models.ManyToManyField(related_name='watching_lists', to='userauth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='permission_level',
            field=models.IntegerField(choices=[(3, 'Admin and Board Members'), (4, 'Admin, Board Members, and team members'), (5, 'anyone')], default=4),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref_invitation',
            field=models.IntegerField(choices=[(1, 'Only admins can add and remove members from this board'), (3, 'Only Members can add and remove members from this board')], default=3),
        ),
    ]
