# Generated by Django 3.1.2 on 2020-11-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0023_auto_20201119_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
