# Generated by Django 3.1.2 on 2020-11-23 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0024_remove_team_members'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='teams.team'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
