# Generated by Django 3.1.2 on 2020-11-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0026_auto_20201123_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
