# Generated by Django 3.1.2 on 2020-11-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0027_delete_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='permission_level',
            field=models.IntegerField(choices=[(3, 'Private'), (4, 'Team'), (5, 'Public')], default=4),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref_comment',
            field=models.IntegerField(choices=[(1, 'Disabled'), (2, 'Admins'), (3, 'Members'), (4, 'team members'), (5, 'Public')], default=1),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref_invitation',
            field=models.IntegerField(choices=[(1, 'Only admins'), (3, 'Members')], default=3),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref_voting',
            field=models.IntegerField(choices=[(1, 'Disabled'), (2, 'Admins'), (3, 'Members'), (4, 'team members'), (5, 'Public')], default=1),
        ),
    ]
