# Generated by Django 3.1.2 on 2020-11-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0003_userprofile_bio'),
        ('cards', '0001_initial'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lists.list'),
        ),
        migrations.AddField(
            model_name='card',
            name='members',
            field=models.ManyToManyField(related_name='member_in_card', to='userauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='card',
            name='voted_by',
            field=models.ManyToManyField(related_name='voted_cards', to='userauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='card',
            name='watched_by',
            field=models.ManyToManyField(related_name='watching_cards', to='userauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='attached_link',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_links', to='cards.card'),
        ),
        migrations.AddField(
            model_name='attached_file',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='cards.card'),
        ),
    ]
