# Generated by Django 3.1.2 on 2020-11-28 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[@_!#$%^&*()<>?/\\|}{~:1234567890]', 'Specail Characters and numbers are not allowed', 'invalid', True)]),
        ),
    ]
